helmDefaults:
  recreatePods: true
  createNamespace: false
  timeout: 600

releases:
  - name: myrelease
    chart: mirror
    namespace: {{ .Values.namespace }}
    disableValidation: true
    values:
      {{- toYaml (list (omit .Values "enabled")) | nindent 6 }}
