helmDefaults:
  recreatePods: true
  createNamespace: false
  timeout: 600

#repositories:
#  - name: mirror
#    url: git+https://github.com/pidoraha/mirror@mirror?ref=master

releases:
  - name: myrelease
    chart: mirror
    namespace: {{ .Values.namespace }}
    disableValidation: true
    values:
      {{- toYaml (list (omit .Values "enabled")) | nindent 6 }}
